### ISSUE TITLE
Update bindings for Yara 4.0.0 release

### ISSUE THREAD

**Issue by baronfel** [airbus-cert/dnYara#3]
Yara has released version [4.0.0](https://github.com/VirusTotal/yara/releases/tag/v4.0.0), which contains a few [breaking API changes](https://github.com/VirusTotal/yara/wiki/Backward-incompatible-changes-in-YARA-4.0-API).

In order to use this repo with version 4.0.0, I think breaking API changes must also be made:

* the bundled submodule of Yara should be updated to the 4.0.0 tag
* because the `YR_RULES` struct is now a shared singleton, I'm not sure that it should implement disposable anymore. this could use to over-eager `using`s that would tear down what is supposed to be a shared resource.
* the `YR_COMPILER_CALLBACK_FUNC` signature must change to include a pointer to the `YR_RULE` (which can of course be null)
* the `YaraScanCallback` delegate must take an IntPtr to the `YR_SCAN_CONTEXT`
* the `Scanner.cs` class should update it's `HandleMessage` routines to receive and use the `YR_SCAN_CONTEXT` pointer to do string match iteration.

Does all this sound reasonable? If so I'd gladly begin that work.

**Comment by sbruyere** [comment]
Thanks @baronfel for your update. I'm reviewing the code of your PR.
I think I'll create a new branch for keeping a version for Yara 3.x.
